### ISSUE TITLE
about 0 bytes images in your dataset

### ISSUE THREAD

**Issue by xuanli98** [VSPW-dataset/VSPW_baseline#1]
hello thanks for the great work. I have entered the competition that your held. I download the data from the link you provide and extract it by the command unzip. I find that there are 0 bytes images "VSPW_480p/data/988_f_Xvy_DCPt8/origin" as it shows in the following image:
![Screenshot from 2021-06-18 15-19-56](https://user-images.githubusercontent.com/30352320/122522593-b81c0980-d048-11eb-9018-9cbb3e546caa.png)
would you like to tell me how I can fix it or could you provide the new download link to me
thank you very much

**Comment by VSPW-dataset** [comment]
Hi, You can download the images of video "988_f_Xvy_DCPt8" by this link:
https://drive.google.com/file/d/1kuQksbhw_sgB5n6fKzts2G9KZn41-q_N/view?usp=sharing
